# Generated by Django 5.2.4 on 2025-07-28 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspectors', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectoravailability',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_availability_slots', to='projects.project'),
        ),
        migrations.AddField(
            model_name='inspectorcertification',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='inspectors.inspector'),
        ),
        migrations.AddField(
            model_name='inspectorcertification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectordocument',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspectors.inspector'),
        ),
        migrations.AddField(
            model_name='inspectordocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_inspector_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectorrating',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='inspectors.inspector'),
        ),
        migrations.AddField(
            model_name='inspectorrating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_ratings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='inspectorrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inspector',
            index=models.Index(fields=['status'], name='inspectors_status_91bbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='inspector',
            index=models.Index(fields=['verification_level'], name='inspectors_verific_18ea70_idx'),
        ),
        migrations.AddIndex(
            model_name='inspector',
            index=models.Index(fields=['is_available'], name='inspectors_is_avai_8e3e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspector',
            index=models.Index(fields=['average_rating'], name='inspectors_average_ffa1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspector',
            index=models.Index(fields=['created_at'], name='inspectors_created_0b3c43_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectoravailability',
            index=models.Index(fields=['inspector', 'date'], name='inspector_a_inspect_6f8ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectoravailability',
            index=models.Index(fields=['status'], name='inspector_a_status_abeca9_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectoravailability',
            index=models.Index(fields=['date', 'start_time'], name='inspector_a_date_733603_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectoravailability',
            unique_together={('inspector', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='inspectorcertification',
            index=models.Index(fields=['status'], name='inspector_c_status_ff586c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectorcertification',
            index=models.Index(fields=['expiry_date'], name='inspector_c_expiry__f8b8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectorcertification',
            index=models.Index(fields=['verified'], name='inspector_c_verifie_d32d12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectorcertification',
            unique_together={('inspector', 'name', 'issuing_organization')},
        ),
        migrations.AddIndex(
            model_name='inspectordocument',
            index=models.Index(fields=['inspector', 'document_type'], name='inspector_d_inspect_8333b6_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectordocument',
            index=models.Index(fields=['status'], name='inspector_d_status_065418_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectordocument',
            index=models.Index(fields=['expiry_date'], name='inspector_d_expiry__3af4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectorrating',
            index=models.Index(fields=['inspector', 'created_at'], name='inspector_r_inspect_fd244f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectorrating',
            index=models.Index(fields=['overall_rating'], name='inspector_r_overall_f3b677_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectorrating',
            index=models.Index(fields=['is_verified'], name='inspector_r_is_veri_a811c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectorrating',
            unique_together={('inspector', 'user', 'project')},
        ),
    ]
